### ISSUE TITLE
Product Name should be in small case

### ISSUE THREAD

**Issue by Gopi30k** [Maanaesh/FreshService-Middleware#3]
https://github.com/Maanaesh/FreshService-Middleware/blob/ee7c0e4d3f83405e71a3f817e9c232b65997534d/fdkMiddleware/config/iparams.html#L31

FreshDesk -> Freshdesk
FreshService -> Freshservice

This should be ensured everywhere in code and document

**Comment by Maanaesh** [comment]
resolved
