### ISSUE TITLE
Q: Why lowercase conversion needed?

### ISSUE THREAD

**Issue by Gopi30k** [Maanaesh/FreshService-Middleware#4]
https://github.com/Maanaesh/FreshService-Middleware/blob/ee7c0e4d3f83405e71a3f817e9c232b65997534d/middleware/controller/handler.js#L16

The field names(backend label) is already extracted from /ticket_fields API in custom app, why do we need lowercase conversion?

**Comment by Maanaesh** [comment]
was using the label names returned now fixed it!
